<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eho" nsURI="http://fr.inria.diverse.melanger.ehomt/eho/" nsPrefix="eho">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" abstract="true">
    <eOperations name="run">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drop" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reject" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eOperations name="run">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accept" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Discard" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacketSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheader" lowerBound="1" upperBound="-1" eType="//ExtensionHeader" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inbound" eSuperTypes="//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outbound" eSuperTypes="//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bandwidth" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="//Unit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="//Time" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BitUnit" eSuperTypes="//Unit"/>
  <eClassifiers xsi:type="ecore:EClass" name="OctetUnit" eSuperTypes="//Unit"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacketUnit" eSuperTypes="//Unit"/>
  <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minute" eSuperTypes="//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hour" eSuperTypes="//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionHeader" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionHopByHop" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HopByHopOpts" eSuperTypes="//ExtensionHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="//OptionHopByHop" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Routing" eSuperTypes="//ExtensionHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1" eType="//TypeRouting" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fragment" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulingSecurityPayload" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthentificationHeader" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestinationOpts" eSuperTypes="//ExtensionHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="//OptionDestination" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobilityHeader" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownEH" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentationAndTesting" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostIdentityProtocol" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shim6Protocol" eSuperTypes="//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pad1" eSuperTypes="//Options">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PadN" eSuperTypes="//Options">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JumboPayload" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPLOption" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TunnelEncapsulationLimit" eSuperTypes="//OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouterAlert" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1" eType="//Protocol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuickStart" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calipso" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmfDpd" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HomeAdress" eSuperTypes="//OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deprecated" eSuperTypes="//Options">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndPointIdentification" eSuperTypes="//Options">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILNPNonce" eSuperTypes="//OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineIdOption" eSuperTypes="//OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPLOption" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment" eSuperTypes="//Options">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpAddSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1" eType="//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packetspec" lowerBound="1" eType="//PacketSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="//IpAddSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="//IpAddSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Protocol" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="protocol">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RSVP" eSuperTypes="//Protocol">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="protocol">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLD" eSuperTypes="//Protocol">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="protocol">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionDestination" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6PerformanceDiagnostic" eSuperTypes="//OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRouting" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceRoute" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nimrod" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type2" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPLSource" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unassigned" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment1" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment2" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reserved" eSuperTypes="//TypeRouting">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="routingType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscardDrop" eSuperTypes="//Configuration">
    <eOperations name="run">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscardReject" eSuperTypes="//Configuration">
    <eOperations name="run">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFF" eSuperTypes="//OptionHopByHop">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options" abstract="true" eSuperTypes="//OptionHopByHop //OptionDestination">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eParameters name="optionType">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
