/*
 * generated by Xtext 2.27.0
 */
package fr.inria.diverse.leho.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LehoRuntimeModule extends AbstractLehoRuntimeModule {
}
