/*
 * generated by Xtext 2.27.0
 */
package fr.inria.diverse.leho.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LehoUiModule extends AbstractLehoUiModule {

	public LehoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
