<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Leho" nsURI="http://www.example.org/Leho" nsPrefix="Leho">
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//Configuration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drop" eType="#//Drop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reject" eType="#//Reject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drop"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packetspec" lowerBound="1"
        eType="#//PacketSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allow" eType="#//Allow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discard" eType="#//Discard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="limitrateto" eType="#//Bandwidth"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reject" eType="#//Reject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drop" upperBound="-1" eType="#//Drop"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Discard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drop" eType="#//Drop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reject" eType="#//Reject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacketSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inbound" eType="#//Inbound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outbound" eType="#//Outbound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheader" upperBound="-1"
        eType="#//ExtensionHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1"
        eType="#//Option" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ipaddspec" upperBound="2"
        eType="#//ipAddSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inbound"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outbound"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bandwidth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasize" lowerBound="1"
        eType="#//DataSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="#//Time"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSize" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bit" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="Octet" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="Packet" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minute" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hour" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionHeader" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HopByHop" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Route" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Frag" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulingSecurityPayload" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthentificationHeader" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Opts" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobilityHeader" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownEH" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentationAndTesting" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostIdentityProtocol" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shim6Protocol" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pad1" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="PadN" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="JumboPayload" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPLOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="TunnelEncapsulationLimit" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouterAlert" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuickStart" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calipso" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmfDpd" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="HomeAdress" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deprecated" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndPointIdentification" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="ILNPNonce" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="LineIdOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="MPLOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPDff" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RfcExperiment" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnkownOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="ipAddSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packet"/>
</ecore:EPackage>
