<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Leho" nsURI="http://www.example.org/Leho" nsPrefix="Leho">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//Configuration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPorts" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packet" upperBound="-1"
        eType="#//Packet.1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentPacket" eType="#//Packet.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drop" eType="#//Drop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reject" eType="#//Reject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drop" eSuperTypes="#//Cmd"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reject" eSuperTypes="#//Cmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packetspec" lowerBound="1"
        eType="#//PacketSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ipaddspec" upperBound="2"
        eType="#//ipAddSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allow" eType="#//Allow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discard" eType="#//Discard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="limitrateto" eType="#//Bandwidth"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reject" eType="#//Reject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drop" upperBound="-1" eType="#//Drop"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allow" eSuperTypes="#//Cmd"/>
  <eClassifiers xsi:type="ecore:EClass" name="Discard"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacketSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inbound" eType="#//Inbound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outbound" eType="#//Outbound"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheader" upperBound="-1"
        eType="#//ExtensionHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inbound"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outbound"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bandwidth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasize" lowerBound="1"
        eType="#//DataSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="#//Time"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSize" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BitSize" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="OctetSize" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacketSize" eSuperTypes="#//DataSize"/>
  <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minute" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hour" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="#//Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionHeader" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HopByHop" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Route" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Frag" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulingSecurityPayload" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthentificationHeader" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPv6Opts" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobilityHeader" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownEH" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentationAndTesting" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="HostIdentityProtocol" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shim6Protocol" eSuperTypes="#//ExtensionHeader"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pad1" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="PadN" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="JumboPayload" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPLOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="TunnelEncapsulationLimit" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouterAlert" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuickStart" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calipso" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmfDpd" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="HomeAdress" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deprecated" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndPointIdentification" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="ILNPNonce" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="LineIdOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="MPLOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPDff" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="RfcExperiment" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnkownOption" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="ipAddSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOp" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOp" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//UnaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equality" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inequality" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterOrEqual" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="LowerOrEqual" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Greater" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lower" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Neg" eSuperTypes="#//UnaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringDec" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanDec" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerDec" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BytesLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BytesDec" eSuperTypes="#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offset" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stmt" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Stmt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Stmt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cmd" abstract="true" eSuperTypes="#//Stmt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstStmt" upperBound="-1"
        eType="#//Stmt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStmt" eType="#//Stmt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetVariable" eSuperTypes="#//Cmd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vardec" lowerBound="1"
        eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
