<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="eho" nsURI="http://fr.inria.diverse.melanger.leho/eho/" nsPrefix="eho">
    <eAnnotations source="http://www.eclipse.org/OCL/Import">
      <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration" abstract="true">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Drop" eSuperTypes="/0/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reject" eSuperTypes="/0/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Accept" eSuperTypes="/0/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Discard" eSuperTypes="/0/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PacketSpec">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="/0/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheader" lowerBound="1" upperBound="-1" eType="/0/ExtensionHeader" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Inbound" eSuperTypes="/0/Interface">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Outbound" eSuperTypes="/0/Interface">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bandwidth" eSuperTypes="/0/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="/0/Unit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="/0/Time" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="BitUnit" eSuperTypes="/0/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="OctetUnit" eSuperTypes="/0/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="PacketUnit" eSuperTypes="/0/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="/0/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Minute" eSuperTypes="/0/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Hour" eSuperTypes="/0/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="/0/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExtensionHeader" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionHopByHop" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HopByHopOpts" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="/0/OptionHopByHop" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Routing" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1" eType="/0/TypeRouting" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fragment" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EncapsulingSecurityPayload" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AuthentificationHeader" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DestinationOpts" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="/0/OptionDestination" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MobilityHeader" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnknownEH" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentationAndTesting" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HostIdentityProtocol" eSuperTypes="/0/ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Shim6Protocol" eSuperTypes="/0/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pad1" eSuperTypes="/0/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PadN" eSuperTypes="/0/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JumboPayload" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RPLOption" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TunnelEncapsulationLimit" eSuperTypes="/0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RouterAlert" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1" eType="/0/Protocol" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuickStart" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Calipso" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmfDpd" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HomeAdress" eSuperTypes="/0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deprecated" eSuperTypes="/0/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndPointIdentification" eSuperTypes="/0/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ILNPNonce" eSuperTypes="/0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LineIdOption" eSuperTypes="/0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MPLOption" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment" eSuperTypes="/0/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpAddSpec">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
        <eParameters name="type">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/0/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1" eType="/0/Action" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packetspec" lowerBound="1" eType="/0/PacketSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="/0/IpAddSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="/0/Rule" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="/0/IpAddSpec" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Protocol" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RSVP" eSuperTypes="/0/Protocol">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MLD" eSuperTypes="/0/Protocol">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionDestination" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPv6PerformanceDiagnostic" eSuperTypes="/0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeRouting" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SourceRoute" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Nimrod" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type2" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RPLSource" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unassigned" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment1" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment2" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reserved" eSuperTypes="/0/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiscardDrop" eSuperTypes="/0/Configuration">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiscardReject" eSuperTypes="/0/Configuration">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFF" eSuperTypes="/0/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Options" abstract="true" eSuperTypes="/0/OptionHopByHop /0/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Policy">
      <eAnnotations source="aspect"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="leho" nsURI="http://fr.inria.diverse.melanger.leho/leho/" nsPrefix="eho">
    <eAnnotations source="http://www.eclipse.org/OCL/Import">
      <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Drop" eSuperTypes="/1/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/1/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reject" eSuperTypes="/1/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Accept" eSuperTypes="/1/Action">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/1/Policy"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Discard" eSuperTypes="/1/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Inbound" eSuperTypes="/1/Interface"/>
    <eClassifiers xsi:type="ecore:EClass" name="Outbound" eSuperTypes="/1/Interface"/>
    <eClassifiers xsi:type="ecore:EClass" name="Bandwidth" eSuperTypes="/1/Action">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="/1/Unit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="/1/Time" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Time" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="BitUnit" eSuperTypes="/1/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="OctetUnit" eSuperTypes="/1/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="PacketUnit" eSuperTypes="/1/Unit"/>
    <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="/1/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Minute" eSuperTypes="/1/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Hour" eSuperTypes="/1/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="/1/Time"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExtensionHeader">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionHopByHop" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HopByHopOpts" eSuperTypes="/1/ExtensionHeader">
      <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="/1/OptionHopByHop" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Routing" eSuperTypes="/1/ExtensionHeader">
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1" eType="/1/TypeRouting" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fragment" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="EncapsulingSecurityPayload" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="AuthentificationHeader" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="DestinationOpts" eSuperTypes="/1/ExtensionHeader">
      <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="/1/OptionDestination" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MobilityHeader" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnknownEH" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentationAndTesting" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="HostIdentityProtocol" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="Shim6Protocol" eSuperTypes="/1/ExtensionHeader"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pad1" eSuperTypes="/1/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PadN" eSuperTypes="/1/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JumboPayload" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RPLOption" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TunnelEncapsulationLimit" eSuperTypes="/1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RouterAlert" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" upperBound="-1" eType="/1/Protocol" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuickStart" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Calipso" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmfDpd" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HomeAdress" eSuperTypes="/1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deprecated" eSuperTypes="/1/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndPointIdentification" eSuperTypes="/1/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ILNPNonce" eSuperTypes="/1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LineIdOption" eSuperTypes="/1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MPLOption" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment" eSuperTypes="/1/Options">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpAddSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1" eType="/1/Port"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1" eType="/1/Action" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="/1/IpAddSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="/1/Rule" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="/1/IpAddSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheader" lowerBound="1" upperBound="-1" eType="/1/ExtensionHeader" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="/1/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Protocol" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RSVP" eSuperTypes="/1/Protocol">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MLD" eSuperTypes="/1/Protocol">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="protocol">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptionDestination" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPv6PerformanceDiagnostic" eSuperTypes="/1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeRouting" abstract="true">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SourceRoute" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Nimrod" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type2" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RPLSource" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unassigned" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment1" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RFC3692Experiment2" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reserved" eSuperTypes="/1/TypeRouting">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="routingType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiscardDrop" eSuperTypes="/1/Configuration">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiscardReject" eSuperTypes="/1/Configuration">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DFF" eSuperTypes="/1/OptionHopByHop">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Options" abstract="true" eSuperTypes="/1/OptionHopByHop /1/OptionDestination">
      <eOperations name="eval">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eParameters name="optionType">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Policy">
      <eOperations name="initializeModel">
        <eAnnotations source="aspect"/>
        <eParameters name="args" upperBound="-1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="run">
        <eAnnotations source="aspect"/>
      </eOperations>
      <eOperations name="read">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
        <eParameters name="offset">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
        <eParameters name="length">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="/1/Filter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packets" upperBound="-1" eType="/1/Packet" transient="true" containment="true">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inPorts" upperBound="-1" eType="/1/Port" transient="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1" eType="/1/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="/1/Configuration" containment="true">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Filter">
      <eOperations name="run">
        <eAnnotations source="aspect"/>
        <eParameters name="root" eType="/1/Policy"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentPacket" eType="/1/Packet">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTime" lowerBound="1" defaultValueLiteral="0">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstRule" eType="/1/Rule" containment="true">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentRule" eType="/1/Rule" containment="true">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Packet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inPort" eType="/1/Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceAddress">
        <eAnnotations source="aspect"/>
        <eAnnotations source="containment"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationAddress">
        <eAnnotations source="aspect"/>
        <eAnnotations source="containment"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensionheaders" upperBound="-1" eType="/1/ExtensionHeader" containment="true">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="/1/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object">
      <eAnnotations source="aspect"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
